sudo: required
services:
    - docker

before_install:
    - docker build -t stefanociceri/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run stefanociceri/react-test npm test -- --coverage

after_success:
    - docker build -t stefanociceri/multidocker-client ./client
    - docker build -t stefanociceri/multidocker-nginx ./nginx
    - docker build -t stefanociceri/multidocker-server ./server
    - docker build -t stefanociceri/multidocker-worker ./worker

    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

    # Push images to Docker Hub
    - docker push stefanociceri/multidocker-client
    - docker push stefanociceri/multidocker-nginx
    - docker push stefanociceri/multidocker-server
    - docker push stefanociceri/multidocker-worker