sudo: required
services:
    - docker

before_install:
    - docker build -t stematrix86/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run stematrix86/react-test npm test -- --coverage

after_success:
    - docker build -t stematrix86/multidocker-client ./client
    - docker build -t stematrix86/multidocker-nginx ./nginx
    - docker build -t stematrix86/multidocker-server ./server
    - docker build -t stematrix86/multidocker-worker ./worker

    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Push images to Docker Hub
    - docker push stematrix86/multidocker-client
    - docker push stematrix86/multidocker-nginx
    - docker push stematrix86/multidocker-server
    - docker push stematrix86/multidocker-worker